name: PRODUCTION

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add label to pull request
      run: |
        # Extract pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        # Add a label to the pull request using GitHub API
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels \
          -d '{"labels": ["NO_CHECKED"]}'

    - run: echo "ðŸ”Ž Setting up node version"
    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: echo "ðŸ”Ž Installing dependencies"
    - name: Install Dependencies
      run: npm install

    - run: echo "ðŸ”Ž Checking linter"
    - name: Linter
      run: npm run lint

    - run: echo "ðŸ”Ž Checking format"
    - name: Format
      run: npm run format

    - name: Remove label from pull request
      run: |
        # Extract pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        # Remove a label from the pull request using GitHub API
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels/NO_CHECKED



